### ISSUE TITLE
Pass arguments to custom sanitizer

### ISSUE THREAD

**Issue by lazarljubenovic** [typestack/class-sanitizer#12]
The docs [describe](https://github.com/typestack/class-sanitizer#custom-sanitation-classes) how to create a custom sanitization class, but it seems impossible to add additional arguments. I'm trying to implement a `Default` sanitizer (see #11), but I'm hitting some limitations with decorators.

After seeing that there are no "official" additional arguments, my first intuition was to use a function which returns a class:

```ts
export default function (defaultValue: any) {
  return class implements SanitizerInterface {
    public sanitize (value: any): any {
      console.log('default sanitizer', value, args)
      return value === undefined ? defaultValue : value
    }
  }
}
```

However, I cannot apply the decorator to a class expression, only to class declarations. I cannot add the default value to constructor either because I'm not the one calling `new`. 

I'll try to find a way to emulate applying decorator on the class expression instead of on a class declaration, but would like an official solution.

**Comment by ChristophKuper** [comment]
[Edit] nevermind misunderstood your issues, sorry

**Comment by NoNameProvided** [comment]
Closing as this library is being deprecated and no new functionality is accepted.
