### ISSUE TITLE
Is this project's development still running?

### ISSUE THREAD

**Issue by rubiin** [typestack/class-sanitizer#14]

**Comment by derevnjuk** [comment]
@rubiin I don't think so. You can use our fork https://github.com/NeuraLegion/class-sanitizer

**Comment by rubiin** [comment]
Cool. Will use it thwn

**Comment by HoldYourWaffle** [comment]
@ArtemDerevnjuk What are the difference between your fork and the base repository?

**Comment by derevnjuk** [comment]
@HoldYourWaffle In short... The fork 

* fixes `each` decorator option
* adds support di container
* adds decorator to strips unsafe tags and attributes from html
* adds support of Set and Map

**Comment by NoNameProvided** [comment]
See #15 for details.
